namespace: process_dataset
name: split_dataset
info:
  type: process_dataset
  type_info:
    label: Data processor
    summary: A spatial decomposition dataset processor.
    description: |
      Prepare a common dataset for the spatial_decomposition task.
arguments:
  - name: "--input"
    __merge__: ../../api/file_simulated_dataset.yaml
    direction: input
    required: true
  - name: "--output_single_cell"
    __merge__: ../../api/file_single_cell.yaml
    direction: output
    required: true
  - name: "--output_spatial_masked"
    __merge__: ../../api/file_spatial_masked.yaml
    direction: output
    required: true
  - name: "--output_solution"
    __merge__: ../../api/file_solution.yaml
    direction: output
    required: true

resources:
    - type: python_script
      path: script.py
    - path: /common/helper_functions/subset_anndata.py

test_resources:
  - type: python_script
    path: /common/component_tests/run_and_check_output.py
  - path: /resources_test/spatial_decomposition/cxg_mouse_pancreas_atlas
    dest: resources_test/spatial_decomposition/cxg_mouse_pancreas_atlas

engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4

runners:
  - type: executable
  - type: nextflow
    directives: 
      label: [midtime, highmem, highcpu]