__merge__: ../../api/comp_method.yaml

name: stereoscope
label: Stereoscope
summary: "Stereoscope is a decomposition method based on Negative Binomial regression."
description: |
  Stereoscope is a decomposition method based on Negative Binomial regression. It is similar in scope and implementation to cell2location but less flexible to incorporate additional covariates such as batch effects and other type of experimental design annotations.
info:
  preferred_normalization: counts
references: 
  doi: 10.1038/s42003-020-01247-y
links:
  documentation: https://docs.scvi-tools.org/en/stable/user_guide/models/stereoscope.html
  repository: https://github.com/scverse/scvi-tools

arguments: 
  - name: "--max_epochs_sc"
    type: integer
    default: 100
    description: Number of of epochs to train RNAStereoscope model.
  - name: "--max_epochs_sp"
    type: integer
    default: 1000
    description: Number of of epochs to train SpatialStereoscope model.

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_pytorch_nvidia:1.0.0
    setup:
      - type: python
        packages: 
          - scvi-tools

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [hightime, midmem, midcpu, gpu]
