__merge__: ../../api/comp_control_method.yaml

name: true_proportions
label: True Proportions
summary: "Positive control method that assigns celltype proportions from the ground truth."
description: |
  A positive control method with perfect assignment of predicted celltype proportions from the ground truth.
info:
  preferred_normalization: counts

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
