__merge__: ../../api/comp_method.yaml

name: nnls
label: NNLS
summary: "NNLS is a decomposition method based on Non-Negative Least Square Regression."
description: |
  NonNegative Least Squares (NNLS), is a convex optimization problem with convex constraints. It was used by the AutoGeneS method to infer cellular proporrtions by solvong a multi-objective optimization problem.
info:
  preferred_normalization: counts
references: 
  doi: 10.1016/j.cels.2021.05.006
links:
  documentation: https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.nnls.html
  repository: https://github.com/scipy/scipy

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        packages: 
          - numpy<2.0
          - scipy

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
