__merge__: ../../api/comp_method.yaml

name: seurat
label: Seurat
summary: "Seurat method that is based on Canonical Correlation Analysis (CCA)."
description: |
  This method applies the 'anchor'-based integration workflow introduced in Seurat v3, that enables the probabilistic transfer of annotations from a reference to a query set. First, mutual nearest neighbors (anchors) are identified from the reference scRNA-seq and query spatial datasets. Then, annotations are transfered from the single cell reference data to the sptial data along with prediction scores for each spot.
info:
  preferred_normalization: counts
references: 
  doi: 10.1016/j.cell.2019.05.031
links:
  documentation: https://satijalab.org/seurat/articles/spatial_vignette
  repository: https://github.com/satijalab/seurat

arguments:
  - name: "--n_pcs"
    type: integer
    default: 30
    description: Number of principal components.
  - name: "--sctransform_n_cells"
    type: integer
    default: 5000
    description: Number of cells sampled to build NB regression.

resources:
  - type: r_script
    path: script.R

engines:
  - type: docker
    image: openproblems/base_r:1.0.0
    setup:
      - type: r
        cran: [Matrix, Seurat]

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, highmem, midcpu]
