__merge__: ../../api/comp_metric.yaml

name: jsd
info:
  metrics:
    - name: jensen_shannon_distance
      label: Jensen-Shannon Distance
      summary: "Jensen-Shannon Distance measure the similarity between to probability distributions."
      description: |
        The Jensen-Shannon Distance, which is the square root of Jensen-Shannon Divergence is a symmetric method for measuring the similarity between two probability distributions. The similarity between the distributions is greater when the Jensen-Shannon distance is closer to zero.
      references: 
        doi: 10.1109/18.61115
      links:
        documentation: https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.jensenshannon.html
        repository: https://github.com/scipy/scipy/
      min: 0
      max: 1
      maximize: false

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        packages: [numpy, scipy]

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
