__merge__: ../../api/comp_method.yaml

name: destvi
label: DestVI
summary: "DestVI is a probabilistic method for multi-resolution analysis for spatial transcriptomics that explicitly models continuous variation within cell types"
description: |
  Deconvolution of Spatial Transcriptomics profiles using Variational Inference (DestVI) is a spatial decomposition method that leverages a conditional generative model of spatial transcriptomics down to the sub-cell-type variation level, which is then used to decompose the cell-type proportions determining the spatial organization of a tissue.
references: 
  doi: 10.1038/s41587-022-01272-8
links: 
  documentation: https://docs.scvi-tools.org/en/stable/user_guide/models/destvi.html
  repository: https://github.com/scverse/scvi-tools
info:
  preferred_normalization: counts

arguments:
  - name: "--max_epochs_sc"
    type: integer
    default: 500
    description: Number of epochs to train the Conditional version of single-cell Variational Inference (CondSCVI) model using MAP inference.
  - name: "--max_epochs_sp"
    type: integer
    default: 10000
    info: 
      test_default: 1000
    description: Number of epochs to train the DestVI model using MAP inference.

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_pytorch_nvidia:1.0.0
    setup:
      - type: python
        packages: 
          - scvi-tools
  
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [veryhightime, midmem, midcpu, gpu]
