__merge__: ../../api/comp_control_method.yaml

name: random_proportions
label: Random Proportions
summary: "Negative control method that randomly assigns celltype proportions from a Dirichlet distribution."
description: |
  A negative control method with random assignment of predicted celltype proportions from a Dirichlet distribution.
info:
  preferred_normalization: counts

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        packages: numpy

runners: 
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
