__merge__: ../../api/comp_method.yaml

name: tangram
label: Tangram
summary: "Tanagram maps single-cell gene expression data onto spatial gene expression data by fitting gene expression on shared genes"
description: |
  Tangram is a method to map gene expression signatures from scRNA-seq data to spatial data. It performs the cell type mapping by learning a similarity matrix between single-cell and spatial locations based on gene expression profiles.
info:
  preferred_normalization: counts
references: 
  doi: 10.1038/s41592-021-01264-7
links:
  documentation: https://tangram-sc.readthedocs.io/en/latest/index.html
  repository: https://github.com/broadinstitute/Tangram

arguments:
  - name: "--num_epochs"
    type: integer
    default: 1000
    description: Number of epochs to use while mapping single cells to spatial locations.
  - name: "--n_markers"
    type: integer
    default: 100
    description: Number of marker genes to use.

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        packages: tangram-sc

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime,midmem, midcpu]
