namespace: data_processors
name: split_dataset
info:
  type: data_processors
  type_info:
    label: Split Dataset
    summary: A spatial decomposition dataset processor.
    description: |
      Prepare a common dataset for the task_spatial_decomposition task.

arguments:
  - name: "--input"
    __merge__: ../../api/file_simulated_dataset.yaml
    direction: input
    required: true
  - name: "--output_single_cell"
    __merge__: ../../api/file_single_cell.yaml
    direction: output
    required: true
  - name: "--output_spatial_masked"
    __merge__: ../../api/file_spatial_masked.yaml
    direction: output
    required: true
  - name: "--output_solution"
    __merge__: ../../api/file_solution.yaml
    direction: output
    required: true

resources:
    - type: python_script
      path: script.py
    - path: /common/helper_functions/subset_h5ad_by_format.py

test_resources:
  # - type: python_script
  #   path: /common/component_tests/check_config.py
  - type: python_script
    path: /common/component_tests/run_and_check_output.py
  - path: /resources_test/task_spatial_decomposition/cxg_mouse_pancreas_atlas
    dest: resources_test/task_spatial_decomposition/cxg_mouse_pancreas_atlas

engines:
  - type: docker
    image: openproblems/base_python:1.0.0

runners:
  - type: executable
  - type: nextflow
    directives: 
      label: [midtime, highmem, highcpu]